# Generated by Django 4.2.14 on 2024-08-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostModels",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=150)),
                ("post_title", models.CharField(max_length=200)),
                ("post_content", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User_Follow_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("user_name", models.CharField(max_length=200)),
                ("like_post", models.BooleanField(default=True)),
                ("like_post_start_date", models.DateField(auto_now_add=True)),
                ("cancel_start_date", models.DateField(auto_now=True)),
            ],
            options={"db_table": "User_Follow_Post",},
        ),
        migrations.CreateModel(
            name="User_Follower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("user_name", models.CharField(max_length=200)),
                ("user_follow_id", models.IntegerField()),
                ("user_follow_name", models.CharField(max_length=200)),
                ("follow_start_date", models.DateField(auto_now_add=True)),
                ("cancel_follow", models.BooleanField(default=False)),
                ("cancel_follow_date", models.DateField(auto_now=True, null=True)),
            ],
            options={"db_table": "User_follow_table",},
        ),
        migrations.CreateModel(
            name="UserProfile_models",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=150)),
                ("user_password", models.CharField(max_length=128)),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("user_birthday", models.DateField(blank=True, null=True)),
                ("tel", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("zip", models.CharField(blank=True, max_length=10, null=True)),
                ("addr", models.CharField(blank=True, max_length=255, null=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZipCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostModels_Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=150)),
                ("comment", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.postmodels"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.userprofile_models",
                    ),
                ),
            ],
            options={"db_table": "post_comment",},
        ),
        migrations.AddField(
            model_name="postmodels",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.userprofile_models"
            ),
        ),
    ]
