# Generated by Django 5.0.7 on 2024-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_models_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_models',
            name='is_superuser',
            field=models.BooleanField(default='FALSE'),
        ),
    ]
