# Generated by Django 5.0.7 on 2024-07-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_models_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_models',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
