# Generated by Django 5.0.7 on 2024-07-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_postmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodels',
            old_name='user_id',
            new_name='user',
        ),
    ]
