# Generated by Django 5.0.7 on 2024-07-28 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_user_id_postmodels_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('user_follow_id', models.IntegerField()),
                ('user_follow_name', models.CharField(max_length=200)),
                ('follow_start_date', models.DateField(auto_now_add=True)),
                ('cancel_follow', models.BooleanField(default=False)),
                ('cancel_follow_date', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'User_follow_table',
            },
        ),
        migrations.CreateModel(
            name='PostModels_Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postmodels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile_models')),
            ],
            options={
                'db_table': 'post_comment',
            },
        ),
    ]
