# Generated by Django 5.0.7 on 2024-07-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_follower_postmodels_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Follow_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('like_post', models.BooleanField(default=True)),
                ('like_post_start_date', models.DateField(auto_now_add=True)),
                ('cancel_start_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'User_Follow_Post',
            },
        ),
    ]
